language: python

python:
    - 2.7
    - 3.5
    - 3.6

before_script:
  - "export DISPLAY=:99.0" # xvfb is used to ensure matplotlib plots don't fail
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        # For this package-template, we include examples of Cython modules,
        # so Cython is required for testing. If your package does not include
        # Cython code, you can set CONDA_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='matplotlib pandas sklearn scipy'
    matrix:
        # Make sure that egg_info works without dependencies
        # - SETUP_CMD='egg_info'
        # Try all python versions with the latest numpy
        - SETUP_CMD='py.test --cov astrodbkit'

#matrix:
#    allow_failures:
#        - python: 3.4

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install requests
    - pip install astroquery

script:
    - $SETUP_CMD

after_success:
    - coveralls
