language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'

install:
    - pip install astropy
    - pip install matplotlib

script:
    - py.test

matrix:
    allow_failures:
        - TRAVIS_PYTHON_VERSION=3.3
        - TRAVIS_PYTHON_VERSION=3.4
        - TRAVIS_PYTHON_VERSION=3.5