INSERT INTO "telescopes" VALUES(1,'SDSS',NULL);
INSERT INTO "telescopes" VALUES(2,'2MASS',NULL);
INSERT INTO "telescopes" VALUES(3,'WISE',NULL);
INSERT INTO "telescopes" VALUES(4,'UKIRT',NULL);
INSERT INTO "telescopes" VALUES(5,'HST',NULL);
INSERT INTO "telescopes" VALUES(6,'Spitzer',NULL);
INSERT INTO "telescopes" VALUES(7,'IRTF',NULL);
INSERT INTO "telescopes" VALUES(8,'Keck I',NULL);
INSERT INTO "telescopes" VALUES(9,'Keck II',NULL);
INSERT INTO "telescopes" VALUES(10,'KPNO 4m',NULL);
INSERT INTO "telescopes" VALUES(11,'KPNO 2.1m',NULL);
INSERT INTO "telescopes" VALUES(12,'KPNO Bok',NULL);
INSERT INTO "telescopes" VALUES(13,'MMT',NULL);
INSERT INTO "telescopes" VALUES(14,'CTIO 1.5m',NULL);
INSERT INTO "telescopes" VALUES(15,'CTIO 4m',NULL);
INSERT INTO "telescopes" VALUES(16,'Gemini North',NULL);
INSERT INTO "telescopes" VALUES(17,'Gemini South',NULL);
INSERT INTO "telescopes" VALUES(18,'ESO VLT U2',NULL);
INSERT INTO "telescopes" VALUES(19,'ARC 3.5m',NULL);
INSERT INTO "telescopes" VALUES(20,'Subaru',NULL);
INSERT INTO "telescopes" VALUES(21,'Magellan II Clay',NULL);
INSERT INTO "telescopes" VALUES(22,'Magellan I Baade',NULL);
INSERT INTO "telescopes" VALUES(23,'ESO 1m',NULL);
INSERT INTO "telescopes" VALUES(24,'CFHT',NULL);
INSERT INTO "telescopes" VALUES(25,'NTT',NULL);
INSERT INTO "telescopes" VALUES(26,'Palomar 200-inch',NULL);
INSERT INTO "telescopes" VALUES(27,'Pan-STARRS 1',NULL);
INSERT INTO "telescopes" VALUES(28,'Palomar 60-inch',NULL);
INSERT INTO "telescopes" VALUES(29,'CTIO 0.9m',NULL);
INSERT INTO "telescopes" VALUES(30,'SOAR 4.1m',NULL);
INSERT INTO "telescopes" VALUES(31,'ESO VLT U3',NULL);
INSERT INTO "telescopes" VALUES(32,'ESO VLT U4',NULL);
INSERT INTO "telescopes" VALUES(33,'GTC',NULL);
